/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Follow extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.FollowRecord> {

	private static final long serialVersionUID = -2070338057;

	/**
	 * The singleton instance of <code>public.follow</code>
	 */
	public static final tech.codingclub.helix.tables.Follow FOLLOW = new tech.codingclub.helix.tables.Follow();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.FollowRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.FollowRecord.class;
	}

	/**
	 * The column <code>public.follow.user_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.FollowRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.follow.following_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.FollowRecord, java.lang.Long> FOLLOWING_ID = createField("following_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>public.follow</code> table reference
	 */
	public Follow() {
		this("follow", null);
	}

	/**
	 * Create an aliased <code>public.follow</code> table reference
	 */
	public Follow(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Follow.FOLLOW);
	}

	private Follow(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.FollowRecord> aliased) {
		this(alias, aliased, null);
	}

	private Follow(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.FollowRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.FollowRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.FollowRecord>>asList(tech.codingclub.helix.Keys.FOLLOW_USER_ID_FOLLOWING_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<tech.codingclub.helix.tables.records.FollowRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<tech.codingclub.helix.tables.records.FollowRecord, ?>>asList(tech.codingclub.helix.Keys.FOLLOW__FOLLOW_USER_ID_FKEY, tech.codingclub.helix.Keys.FOLLOW__FOLLOW_FOLLOWING_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Follow as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Follow(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Follow rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Follow(name, null);
	}
}
